### ISSUE TITLE
Bug: Invalid highlight color: '15'

### ISSUE THREAD

**Issue by vitvly** [ibhagwan/fzf-lua#1571]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

Mac

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.10.2

### Fzf version (`fzf --version`)

0.57.0 (brew)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--bind "alt-enter:execute(open {})+accept" --bind "ctrl-i:up" --bind "ctrl-j:down" --color=light

### Is the problem reproducible with `mini.sh`?

- [ ] My issue is reproducible with `mini.sh`
- [X] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
fzflua = require('fzf-lua')
fzflua.setup({
  defaults={file_icons = false, previewer = false, 
    winopts = {
      preview = {
        delay = 0,
      },
    },
  },
  grep = {
    actions = { ["ctrl-e"] = { fn = require"fzf-lua".actions.file_sel_to_qf, prefix = "select-all" }}
  },
  live_grep = {
    actions = { ["ctrl-e"] = { fn = require"fzf-lua".actions.file_sel_to_qf, prefix = "select-all" }}
  },
  files = {
    actions = { ["ctrl-e"] = { fn = require"fzf-lua".actions.file_sel_to_qf, prefix = "select-all" }}
  },
})
```

### Describe the bug / steps to reproduce

When executing `:FzfLua files`, i get this error:
```
Error executing Lua callback: ~/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:245: ~/.loca
l/share/nvim/plugged/fzf-lua/lua/fzf-lua/win.lua:539: Invalid highlight color: '15'
stack traceback:
        [builtin#36]: at 0x0101221070
        ~/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/core.lua:245: in function <~/.local/share/nv
im/plugged/fzf-lua/lua/fzf-lua/core.lua:223>
        ~/.local/share/nvim/plugged/fzf-lua/lua/fzf-lua/cmd.lua:35: in function 'run_command'
        ~/.local/share/nvim/plugged/fzf-lua/plugin/fzf-lua.lua:12: in function <~/.local/share/n
vim/plugged/fzf-lua/plugin/fzf-lua.lua:11>
```
This started appearing after upgrade to most recent version, and in particular, is caused by this commit: https://github.com/ibhagwan/fzf-lua/commit/f07f0d310c12cbd62ab48148cd760cfa606e8117.

If i add `scrollbar = "float"` to `winopts.preview` table in the fzf-lua config, the problem is gone.

**Comment by ibhagwan** [comment]
Can you use `:FzfLua highlights` and follow `FzfLuaScrollBorderFull` (if hl is linked, follow to the the definition) and let me know what’s the fg/bg for the group?

**Comment by ibhagwan** [comment]
@vitvly, should be fixed with https://github.com/ibhagwan/fzf-lua/commit/1511da02661654caeb1bca9a1871e2b7731f5836 - let me know?

**Comment by vitvly** [comment]
@ibhagwan unfortunately, doesn't seem to work - has no effect on the behaviours described above.

**Comment by ibhagwan** [comment]
> @ibhagwan unfortunately, doesn't seem to work - has no effect on the behaviours described above.

Alright, so can you tell me what's the highlight you're getting for `FzfLuaScrollBorderFull` as the issue lies there.

Use `float` to get fzf-lua working and use `:FzfLua highlights` to explore and let me know the fg/bg and I'll fix it.

**Comment by vitvly** [comment]
With the most recent code, i still cannot run `:FzfLua highlights`, it throws the same `Invalid highlight color: '15'` error, even with `scrollbar="float"`. Is there another way for me to fetch the highlight groups?

**Comment by ibhagwan** [comment]
> With the most recent code, i still cannot run `:FzfLua highlights`, it throws the same `Invalid highlight color: '15'` error, even with `scrollbar="float"`. Is there another way for me to fetch the highlight groups?

Can you show me the exception line of code? with `float` it should never get to the code that failed in the OP.

You can proabably also workaround this by setting `:colorscheme default` but then we won't know which hl group is causing the issue :-)

Which colorscheme are you using?

**Comment by ibhagwan** [comment]
@vitvly, I believe I found the exact source, you don't have `termguicolors` enabled - https://github.com/ibhagwan/fzf-lua/commit/304253e4c637fd5fc92cbc50707993130615808a should solve the issue.

Please reopen this issue if it doesn't.
