### ISSUE TITLE
Bug: `vim.ui.select()` implementation doesn't restore Insert mode for `on_choice` execution

### ISSUE THREAD

**Issue by echasnovski** [ibhagwan/fzf-lua#1572]
### RTFM Checklist

- [X] I have searched exisiting issues / discussions
- [X] I have read the Wiki including the Advanced section
- [X] I have read `man fzf` / I am well versed in shell fzf

### Operating system

EndeavourOS Linux x86_64, 6.12.4-arch1-1

### Shell

zsh

### Neovim version (`nvim --version`)

NVIM v0.11.0-dev-1357+gcc38630d39

### Fzf version (`fzf --version`)

0.56.3 (add1aec6)

### Output of `:lua print(os.getenv('FZF_DEFAULT_OPTS'))`

--layout=reverse --inline-info --height 25%

### Is the problem reproducible with `mini.sh`?

- [X] My issue is reproducible with `mini.sh`
- [ ] My issue **IS NOT** reproducible with `mini.sh`
- [ ] I have not tested with `mini.sh` (not relevant, requires LSP, Windows, etc)

### Fzf-lua configuration

```lua
require('fzf-lua').setup()
```

### Describe the bug / steps to reproduce

1. Create the following script file:
    ```lua
    require("fzf-lua").register_ui_select()

    _G.log = {}
    local add_log = function()
      local t = { mode = vim.fn.mode(), win_id = vim.api.nvim_get_current_win(), cursor = vim.api.nvim_win_get_cursor(0) }
      table.insert(_G.log, t)
    end

    local on_choice = function()
      add_log()
      vim.schedule(add_log)
    end
    vim.keymap.set("i", "<M-m>", function() vim.ui.select({ "a", "b" }, {}, on_choice) end)
    ```
2. `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"`
3. `:source <path/to/script>`
4. Type `abcdef` and place cursor at `d` in Insert mode.
5. Press `<M-m>` to show `vim.ui.select()` from Fzf-lua.
6. Press `<CR>` to accept first entry. Notice that Normal mode is now active and not Insert.
7. `:=log`. It has two entries (one immediate, one from `vim.schedule()`) and both show `mode = 't'` but correct cursor and window.

**Comment by ibhagwan** [comment]
Ty @echasnovski for the report, should be fixed with https://github.com/ibhagwan/fzf-lua/commit/661b5de13b6b55cde035373e39e4321210acc4b0.

**Comment by echasnovski** [comment]
Unfortunately, it looks like the fix is only partial. Insert mode is indeed restored *after* `vim.ui.select()` finished as a whole, but not at the moment when `on_choice()` is execute (either immediately or with `vim.schedule()`). Running steps from this issue still shows Terminal mode active in both entries.

**Comment by ibhagwan** [comment]
I see @echasnovski, we can reopen and explore this, as for the issue, fzf-lua has to be run in "normal terminal" mode to enable navigation selection, there's no way around that, as for the INSERT mode the latest commit restored that **before** running `on_choice` (see line 131 below).

Perhaps I can coroutine.yield it until INSERT mode is verified (due to the delay you mentioned) before running `on_choice` but that would be hacky and ugly.

https://github.com/ibhagwan/fzf-lua/blob/1511da02661654caeb1bca9a1871e2b7731f5836/lua/fzf-lua/providers/ui_select.lua#L113-L133

**Comment by echasnovski** [comment]
> ... as for the INSERT mode the latest commit restored that **before** running `on_choice` (see line 131 below).

I did see this, but actual testing shows that it is not enough to actually ensure Insert mode for `on_choice()`: actual returned value of `vim.fn.mode()` at the start of `on_choice()` shows `"t"` (i.e. Terminal mode). And also the same mode value is shown in `vim.schedule()` variant (which is a bit strange), so there is little actual users can do here.

**Comment by ibhagwan** [comment]
https://github.com/ibhagwan/fzf-lua/commit/86faa5a23e7158c2f49941591c0889c3746389da

Ty for the suggesion @echasnovski, this seems to work, I now get `i` before the `on_choice`.

Let me know if this works for you as well and we can close this issue.

**Comment by ibhagwan** [comment]
> However, on my side it (for some reason 🤔) doesn't work

How can the mode return anything other than `i` after the autocmd callback?

>  I think I patched this on my end by having a hacky hack like this:
 
If it works :-)

**Comment by echasnovski** [comment]
> > However, on my side it (for some reason 🤔) doesn't work
> 
> How can the mode return anything other than `i` after the autocmd callback?

I didn't check the actual mode value, but it didn't work with my actual use case.

Now that I've checked, it is even weirder: repro steps work (i.e. no issue) with `mini.sh` but don't work (i.e. yes issue) when I use 'fzf-lua' in my usual setup. I double checked that 'fzf-lua' is on latest `main`. I'll have to bisect config to find the cause.

**Comment by rafikdraoui** [comment]
This actually fixes something I was puzzling over just yesterday! My use case is a unicode character picker, which I trigger through an insert mode mapping that calls something like:

```lua
vim.ui.select(data, {prompt = "..."}, function(choice)
  if choice then
    vim.api.nvim_input(choice[2])
  end
end)
```

This didn't work yesterday with fzf-lua as the `vim.ui.select` provider, and I thought I would need to write a custom fzf-lua integration to handle it. But now it works out of the box 🙂

**Comment by ibhagwan** [comment]
Ty for the update happy to hear that @rafikdraoui!
