### ISSUE TITLE
Which previewer is the fastest?

### ISSUE THREAD

**Issue by nyngwang** [ibhagwan/fzf-lua#203]
As title. I want speed and I can sacrifice colors.

**Comment by ibhagwan** [comment]
> As title. I want speed and I can sacrifice colors.

Due to treesitter/syntax highlights the neovim previewer would be the slowest. You can try changing the default previewer (`winopts.preview.default`) to `bat`, you’d get decent speed and still have syntax highlights, those will be different than your current color scheme (configurable if you wish to change it `bat --list-themes`).

If it’s still too slow for you and you’re willing to sacrifice colors you can change the previewer to `cat`, if that is too slow you can even go with `head` as previewer which shows only the relevant context instead of the entire file.

Also worth noting that if you don’t care about colors or icons and you wish to have max performance you can also [read this from the Wiki](https://github.com/ibhagwan/fzf-lua/wiki#max-perf).

**Comment by nyngwang** [comment]
I cannot setup `cat` correctly following the README.md. I got this:

<img src="https://user-images.githubusercontent.com/24765272/140396605-58501405-8a55-4706-a661-a9fe5cbf8931.png" width="700">

**Comment by ibhagwan** [comment]
Seems like we have different `cat` versions, the default command adds the line number with `cat --number` which seems to bot be supported with your version, add this to your setup function to override the default function:

```lua
require'fzf-lua'.setup {
  previewers = {
    cat = {
      cmd = "cat",
      args = "",
    },
  }
}
```

**Comment by nyngwang** [comment]
I still got the same error:

<img src="https://user-images.githubusercontent.com/24765272/140462235-4e608a4c-4d61-465e-9aaf-a90957719f24.png" width="700">

**Comment by ibhagwan** [comment]
Can you try with `winopts.preview.default = 'bat_native'`?

**Comment by nyngwang** [comment]
To provide more information, I think maybe the content of the comment matters:

## Comment ends with `.lua`

```
          -- WARNING: Copy-paste from https://github.com/tjdevries/config_manager/blob/master/xdg_config/nvim/after/plugin/completion.lua
```
<img src="https://user-images.githubusercontent.com/24765272/140462731-6e3ddf8b-d647-463a-9e4a-b396bb687a28.png" width="700">

**Comment by ibhagwan** [comment]
>To provide more information, I think maybe the content of the comment matters:

It's possible, does `bat` or `cat` work when using `:FzfLua files` (when there is no file content at all)?

**Comment by nyngwang** [comment]
> Can you try with `winopts.preview.default = 'bat_native'`?

This one works! Wow!

**Comment by ibhagwan** [comment]
> > Can you try with `winopts.preview.default = 'bat_native'`?
> 
> This one works! Wow!

Great! I'd still like to solve it for `bat`/`cat`, does this work at all for different contents? can you tell what file contents consistently fails? Maybe we should discuss this under #204?

**Comment by nyngwang** [comment]
> > > Can you try with `winopts.preview.default = 'bat_native'`?
> > 
> > 
> > This one works! Wow!
> 
> Great! I'd still like to solve it for `bat`/`cat`, does this work at all for different contents? can you tell what file contents consistently fails? Maybe we should discuss this under #204?

OK, I'm really happy to help, let's move to #204 now.

**Comment by ibhagwan** [comment]
> > > > Can you try with `winopts.preview.default = 'bat_native'`?
> > > 
> > > 
> > > This one works! Wow!
> > 
> > 
> > Great! I'd still like to solve it for `bat`/`cat`, does this work at all for different contents? can you tell what file contents consistently fails? Maybe we should discuss this under #204?
> 
> OK, I'm really happy to help, let's move to #204 now.

Tysm, I guess we can close this one for now.

**Comment by ibhagwan** [comment]
Ok, now that we fixed #204, does `cat` work better for you than `bat` / `bat_native`?

**Comment by nyngwang** [comment]
Both make neovim frozen on 200+ results where some of them are large files.

**Comment by ibhagwan** [comment]
> Both make neovim frozen on 200+ results where some of them are large files.

How large? Are they text files or binary files? What filetype?
Does it also get stuck with the default previewer?

**Comment by nyngwang** [comment]
Text file. Files that appear in `node_modules/` and those library files that is uglified to serve for browser. They usually contain 1000+ lines. I go with `head` for previewer, the problem still happened.
